services:
  crosspost-server:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DB_PATH: /data/data.sqlite
    volumes:
      - sqlite_data:/data

  crosspost-tg-worker:
    build: .
    command: node src/telegram_worker.js
    restart: unless-stopped
    env_file: .env
    environment:
      DB_PATH: /data/data.sqlite
    volumes:
      - sqlite_data:/data
    depends_on:
      - crosspost-server

volumes:
  sqlite_data:
